#!/bin/sh
set -eu

mode="${1:-ensure}"
export MYSQL_PWD="$MYSQL_ROOT_PASSWORD"

if [ "$mode" = "fresh" ]; then
  mysql --user=root \
    --execute="DROP DATABASE IF EXISTS \`$MYSQL_DATABASE\`;"
fi

mysql --user=root <<SQL
CREATE DATABASE IF NOT EXISTS \`$MYSQL_DATABASE\`
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
ALTER USER '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON \`$MYSQL_DATABASE\`.* TO '$MYSQL_USER'@'%';
FLUSH PRIVILEGES;
SQL
