services:
  gateway:
    build:
      context: ..
      dockerfile: gateway/Dockerfile
    container_name: tumlumtala-gateway
    ports:
      - "${HOST_PORT}:${APP_PORT}"
    env_file:
      - .env
    networks:
      - tumlumtala-net
    restart: unless-stopped

networks:
  tumlumtala-net:
    driver: bridge
    external: true
