services:
  gateway:
    build:
      context: ..
      dockerfile: gateway/Dockerfile
    container_name: tumlumtala-gateway
    ports:
      - "${HOST_PORT}:${APP_PORT}"
    env_file:
      - .env
    environment:
      TRACING_ENABLED: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      APP_VERSION: local
      LOCAL_UPLOAD_DIR: /app/uploads
      LOCAL_UPLOAD_BASE_URL: /uploads
    volumes:
      - ../uploads:/app/uploads
    networks:
      - tumlumtala-net
    restart: unless-stopped

networks:
  tumlumtala-net:
    driver: bridge
    external: true
