services:
  movies-service:
    build:
      context: ..
      dockerfile: movies-service/Dockerfile
    container_name: tumlumtala-movies-service
    env_file: .env
    environment:
      DB_HOST: tumlumtala-users-mysql
      DB_PORT: "3306"
    ports:
      - "${PORT:-25055}:${PORT:-25055}"
    networks:
      - tumlumtala-net
    restart: unless-stopped

networks:
  tumlumtala-net:
    external: true
