// Package envelope defines the standard message wrapper used across all Kafka
// topics. Every message published by any service MUST be wrapped in Envelope
// so consumers have the metadata they need for tracing, retry, and DLQ.
package envelope

import "time"

// Envelope wraps a domain event payload with operational metadata.
// Mirrors the same concept used in the RabbitMQ notification pipeline.
type Envelope struct {
	// EventID is a UUID generated by the publisher. Used for idempotency.
	EventID string `json:"event_id"`

	// Topic the message was originally published to.
	Topic string `json:"topic"`

	// Attempt starts at 1 (first delivery). Consumers increment before retry.
	Attempt int `json:"attempt"`

	// MaxRetries mirrors the consumer configuration so DLQ processors know.
	MaxRetries int `json:"max_retries"`

	// TraceID propagated from the originating HTTP/gRPC request.
	TraceID string `json:"trace_id,omitempty"`

	// RequestID propagated from the originating HTTP/gRPC request.
	RequestID string `json:"request_id,omitempty"`

	// PublishedAt is set by the publisher; updated on each retry.
	PublishedAt time.Time `json:"published_at"`

	// Payload is the raw JSON-encoded domain event.
	Payload []byte `json:"payload"`
}

// DeadLetter is persisted to the DLQ topic when an envelope exceeds MaxRetries
// or contains an unparseable payload.
type DeadLetter struct {
	// Original envelope (may be zero if payload was unparseable).
	Envelope Envelope `json:"envelope"`

	// RawPayload holds the raw bytes when envelope parsing failed.
	RawPayload []byte `json:"raw_payload,omitempty"`

	// Reason is a short machine-readable code: "max_retries_exceeded" | "invalid_payload".
	Reason string `json:"reason"`

	// LastError is the last handler error message.
	LastError string `json:"last_error"`

	// FailedAt is when the message was sent to DLQ.
	FailedAt time.Time `json:"failed_at"`
}
