package seeders

import (
	"fmt"
	"time"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"

	"github.com/tumlumtala/messenger-service/internal/infrastructure/persistence/model"
)

type EmojiSeeder struct{}

func (s *EmojiSeeder) Name() string { return "EmojiSeeder" }

type emojiDef struct {
	code     string
	name     string
	icon     string
	packCode string
}

var faceData = []emojiDef{
	{code: "grinning_face", name: "Grinning Face", icon: "😀", packCode: "face"},
	{code: "grinning_face_big_eyes", name: "Grinning Face Big Eyes", icon: "😃", packCode: "face"},
	{code: "grinning_face_smiling_eyes", name: "Grinning Face Smiling Eyes", icon: "😄", packCode: "face"},
	{code: "beaming_face", name: "Beaming Face", icon: "😁", packCode: "face"},
	{code: "grinning_squinting_face", name: "Grinning Squinting Face", icon: "😆", packCode: "face"},
	{code: "grinning_face_sweat", name: "Grinning Face Sweat", icon: "😅", packCode: "face"},
	{code: "face_tears_joy", name: "Face Tears of Joy", icon: "😂", packCode: "face"},
	{code: "rolling_on_floor_laughing", name: "Rolling on Floor Laughing", icon: "🤣", packCode: "face"},
	{code: "smiling_face", name: "Smiling Face", icon: "😊", packCode: "face"},
	{code: "smiling_face_halo", name: "Smiling Face Halo", icon: "😇", packCode: "face"},
	{code: "slightly_smiling_face", name: "Slightly Smiling Face", icon: "🙂", packCode: "face"},
	{code: "upside_down_face", name: "Upside Down Face", icon: "🙃", packCode: "face"},
	{code: "winking_face", name: "Winking Face", icon: "😉", packCode: "face"},
	{code: "relieved_face", name: "Relieved Face", icon: "😌", packCode: "face"},
	{code: "heart_eyes", name: "Heart Eyes", icon: "😍", packCode: "face"},
	{code: "smiling_hearts", name: "Smiling Face With Hearts", icon: "🥰", packCode: "face"},
	{code: "face_blowing_kiss", name: "Face Blowing Kiss", icon: "😘", packCode: "face"},
	{code: "kissing_face", name: "Kissing Face", icon: "😗", packCode: "face"},
	{code: "kissing_smiling_eyes", name: "Kissing Smiling Eyes", icon: "😙", packCode: "face"},
	{code: "kissing_closed_eyes", name: "Kissing Closed Eyes", icon: "😚", packCode: "face"},
	{code: "face_savoring_food", name: "Face Savoring Food", icon: "😋", packCode: "face"},
	{code: "tongue_face", name: "Face With Tongue", icon: "😛", packCode: "face"},
	{code: "squinting_tongue_face", name: "Squinting Tongue Face", icon: "😝", packCode: "face"},
	{code: "winking_tongue_face", name: "Winking Tongue Face", icon: "😜", packCode: "face"},
	{code: "zany_face", name: "Zany Face", icon: "🤪", packCode: "face"},
	{code: "raised_eyebrow", name: "Raised Eyebrow", icon: "🤨", packCode: "face"},
	{code: "monocle_face", name: "Monocle Face", icon: "🧐", packCode: "face"},
	{code: "nerd_face", name: "Nerd Face", icon: "🤓", packCode: "face"},
	{code: "sunglasses_face", name: "Sunglasses Face", icon: "😎", packCode: "face"},
	{code: "disguised_face", name: "Disguised Face", icon: "🥸", packCode: "face"},
	{code: "star_struck", name: "Star Struck", icon: "🤩", packCode: "face"},
	{code: "party_face", name: "Party Face", icon: "🥳", packCode: "face"},
	{code: "smirking_face", name: "Smirking Face", icon: "😏", packCode: "face"},
	{code: "unamused_face", name: "Unamused Face", icon: "😒", packCode: "face"},
	{code: "disappointed_face", name: "Disappointed Face", icon: "😞", packCode: "face"},
	{code: "pensive_face", name: "Pensive Face", icon: "😔", packCode: "face"},
	{code: "worried_face", name: "Worried Face", icon: "😟", packCode: "face"},
	{code: "confused_face", name: "Confused Face", icon: "😕", packCode: "face"},
	{code: "slightly_frowning_face", name: "Slightly Frowning Face", icon: "🙁", packCode: "face"},
	{code: "frowning_face", name: "Frowning Face", icon: "☹️", packCode: "face"},
	{code: "persevering_face", name: "Persevering Face", icon: "😣", packCode: "face"},
	{code: "confounded_face", name: "Confounded Face", icon: "😖", packCode: "face"},
	{code: "tired_face", name: "Tired Face", icon: "😫", packCode: "face"},
	{code: "weary_face", name: "Weary Face", icon: "😩", packCode: "face"},
	{code: "pleading_face", name: "Pleading Face", icon: "🥺", packCode: "face"},
	{code: "crying_face", name: "Crying Face", icon: "😢", packCode: "face"},
	{code: "loudly_crying_face", name: "Loudly Crying Face", icon: "😭", packCode: "face"},
	{code: "face_steam_nose", name: "Face With Steam From Nose", icon: "😤", packCode: "face"},
	{code: "angry_face", name: "Angry Face", icon: "😠", packCode: "face"},
	{code: "pouting_face", name: "Pouting Face", icon: "😡", packCode: "face"},
	{code: "face_symbols_mouth", name: "Face With Symbols On Mouth", icon: "🤬", packCode: "face"},
	{code: "exploding_head", name: "Exploding Head", icon: "🤯", packCode: "face"},
	{code: "flushed_face", name: "Flushed Face", icon: "😳", packCode: "face"},
	{code: "hot_face", name: "Hot Face", icon: "🥵", packCode: "face"},
	{code: "cold_face", name: "Cold Face", icon: "🥶", packCode: "face"},
	{code: "screaming_fear", name: "Face Screaming In Fear", icon: "😱", packCode: "face"},
	{code: "fearful_face", name: "Fearful Face", icon: "😨", packCode: "face"},
	{code: "anxious_face", name: "Anxious Face With Sweat", icon: "😰", packCode: "face"},
	{code: "sad_but_relieved", name: "Sad But Relieved Face", icon: "😥", packCode: "face"},
	{code: "downcast_sweat", name: "Downcast Face With Sweat", icon: "😓", packCode: "face"},
	{code: "hugging_face", name: "Hugging Face", icon: "🤗", packCode: "face"},
	{code: "thinking_face", name: "Thinking Face", icon: "🤔", packCode: "face"},
	{code: "saluting_face", name: "Saluting Face", icon: "🫡", packCode: "face"},
	{code: "face_hand_over_mouth", name: "Face Hand Over Mouth", icon: "🤭", packCode: "face"},
	{code: "shushing_face", name: "Shushing Face", icon: "🤫", packCode: "face"},
	{code: "baby", name: "Baby", icon: "👶", packCode: "face"},
	{code: "child", name: "Child", icon: "🧒", packCode: "face"},
	{code: "boy", name: "Boy", icon: "👦", packCode: "face"},
	{code: "girl", name: "Girl", icon: "👧", packCode: "face"},
	{code: "person", name: "Person", icon: "🧑", packCode: "face"},
	{code: "man", name: "Man", icon: "👨", packCode: "face"},
	{code: "woman", name: "Woman", icon: "👩", packCode: "face"},
	{code: "older_person", name: "Older Person", icon: "🧓", packCode: "face"},
	{code: "old_man", name: "Old Man", icon: "👴", packCode: "face"},
	{code: "old_woman", name: "Old Woman", icon: "👵", packCode: "face"},
	{code: "thumbs_up", name: "Thumbs Up", icon: "👍", packCode: "face"},
	{code: "thumbs_down", name: "Thumbs Down", icon: "👎", packCode: "face"},
	{code: "ok_hand", name: "OK Hand", icon: "👌", packCode: "face"},
	{code: "victory_hand", name: "Victory Hand", icon: "✌️", packCode: "face"},
	{code: "crossed_fingers", name: "Crossed Fingers", icon: "🤞", packCode: "face"},
	{code: "love_you_gesture", name: "Love You Gesture", icon: "🤟", packCode: "face"},
	{code: "rock_on", name: "Sign Of The Horns", icon: "🤘", packCode: "face"},
	{code: "call_me_hand", name: "Call Me Hand", icon: "🤙", packCode: "face"},
	{code: "clapping_hands", name: "Clapping Hands", icon: "👏", packCode: "face"},
	{code: "raising_hands", name: "Raising Hands", icon: "🙌", packCode: "face"},
	{code: "heart_hands", name: "Heart Hands", icon: "🫶", packCode: "face"},
	{code: "folded_hands", name: "Folded Hands", icon: "🙏", packCode: "face"},
	{code: "waving_hand", name: "Waving Hand", icon: "👋", packCode: "face"},
	{code: "handshake", name: "Handshake", icon: "🤝", packCode: "face"},
}

var animalData = []emojiDef{
	{code: "dog", name: "Dog", icon: "🐶", packCode: "animal"},
	{code: "cat", name: "Cat", icon: "🐱", packCode: "animal"},
	{code: "mouse", name: "Mouse", icon: "🐭", packCode: "animal"},
	{code: "hamster", name: "Hamster", icon: "🐹", packCode: "animal"},
	{code: "rabbit", name: "Rabbit", icon: "🐰", packCode: "animal"},
	{code: "fox", name: "Fox", icon: "🦊", packCode: "animal"},
	{code: "bear", name: "Bear", icon: "🐻", packCode: "animal"},
	{code: "polar_bear", name: "Polar Bear", icon: "🐻‍❄️", packCode: "animal"},
	{code: "panda", name: "Panda", icon: "🐼", packCode: "animal"},
	{code: "koala", name: "Koala", icon: "🐨", packCode: "animal"},
	{code: "tiger", name: "Tiger", icon: "🐯", packCode: "animal"},
	{code: "lion", name: "Lion", icon: "🦁", packCode: "animal"},
	{code: "cow", name: "Cow", icon: "🐮", packCode: "animal"},
	{code: "pig", name: "Pig", icon: "🐷", packCode: "animal"},
	{code: "frog", name: "Frog", icon: "🐸", packCode: "animal"},
	{code: "monkey", name: "Monkey", icon: "🐵", packCode: "animal"},
	{code: "orangutan", name: "Orangutan", icon: "🦧", packCode: "animal"},
	{code: "gorilla", name: "Gorilla", icon: "🦍", packCode: "animal"},
	{code: "wolf", name: "Wolf", icon: "🐺", packCode: "animal"},
	{code: "boar", name: "Boar", icon: "🐗", packCode: "animal"},
	{code: "horse", name: "Horse", icon: "🐴", packCode: "animal"},
	{code: "unicorn", name: "Unicorn", icon: "🦄", packCode: "animal"},
	{code: "zebra", name: "Zebra", icon: "🦓", packCode: "animal"},
	{code: "deer", name: "Deer", icon: "🦌", packCode: "animal"},
	{code: "bison", name: "Bison", icon: "🦬", packCode: "animal"},
	{code: "goat", name: "Goat", icon: "🐐", packCode: "animal"},
	{code: "ram", name: "Ram", icon: "🐏", packCode: "animal"},
	{code: "sheep", name: "Sheep", icon: "🐑", packCode: "animal"},
	{code: "camel", name: "Camel", icon: "🐪", packCode: "animal"},
	{code: "two_hump_camel", name: "Two-Hump Camel", icon: "🐫", packCode: "animal"},
	{code: "llama", name: "Llama", icon: "🦙", packCode: "animal"},
	{code: "giraffe", name: "Giraffe", icon: "🦒", packCode: "animal"},
	{code: "elephant", name: "Elephant", icon: "🐘", packCode: "animal"},
	{code: "rhinoceros", name: "Rhino", icon: "🦏", packCode: "animal"},
	{code: "hippopotamus", name: "Hippo", icon: "🦛", packCode: "animal"},
	{code: "kangaroo", name: "Kangaroo", icon: "🦘", packCode: "animal"},
	{code: "sloth", name: "Sloth", icon: "🦥", packCode: "animal"},
	{code: "otter", name: "Otter", icon: "🦦", packCode: "animal"},
	{code: "skunk", name: "Skunk", icon: "🦨", packCode: "animal"},
	{code: "beaver", name: "Beaver", icon: "🦫", packCode: "animal"},
	{code: "mammoth", name: "Mammoth", icon: "🦣", packCode: "animal"},
	{code: "chipmunk", name: "Chipmunk", icon: "🐿️", packCode: "animal"},
	{code: "hedgehog", name: "Hedgehog", icon: "🦔", packCode: "animal"},
	{code: "badger", name: "Badger", icon: "🦡", packCode: "animal"},
	{code: "guide_dog", name: "Guide Dog", icon: "🦮", packCode: "animal"},
	{code: "service_dog", name: "Service Dog", icon: "🐕‍🦺", packCode: "animal"},
	{code: "poodle", name: "Poodle", icon: "🐩", packCode: "animal"},
	{code: "black_cat", name: "Black Cat", icon: "🐈‍⬛", packCode: "animal"},
	{code: "paw_prints", name: "Paw Prints", icon: "🐾", packCode: "animal"},
	{code: "chicken", name: "Chicken", icon: "🐔", packCode: "animal"},
	{code: "rooster", name: "Rooster", icon: "🐓", packCode: "animal"},
	{code: "hatching_chick", name: "Hatching Chick", icon: "🐣", packCode: "animal"},
	{code: "baby_chick", name: "Baby Chick", icon: "🐤", packCode: "animal"},
	{code: "front_facing_baby_chick", name: "Front Facing Baby Chick", icon: "🐥", packCode: "animal"},
	{code: "bird", name: "Bird", icon: "🐦", packCode: "animal"},
	{code: "penguin", name: "Penguin", icon: "🐧", packCode: "animal"},
	{code: "dove", name: "Dove", icon: "🕊️", packCode: "animal"},
	{code: "eagle", name: "Eagle", icon: "🦅", packCode: "animal"},
	{code: "duck", name: "Duck", icon: "🦆", packCode: "animal"},
	{code: "swan", name: "Swan", icon: "🦢", packCode: "animal"},
	{code: "owl", name: "Owl", icon: "🦉", packCode: "animal"},
	{code: "dodo", name: "Dodo", icon: "🦤", packCode: "animal"},
	{code: "flamingo", name: "Flamingo", icon: "🦩", packCode: "animal"},
	{code: "peacock", name: "Peacock", icon: "🦚", packCode: "animal"},
	{code: "parrot", name: "Parrot", icon: "🦜", packCode: "animal"},
	{code: "turtle", name: "Turtle", icon: "🐢", packCode: "animal"},
	{code: "snake", name: "Snake", icon: "🐍", packCode: "animal"},
	{code: "lizard", name: "Lizard", icon: "🦎", packCode: "animal"},
	{code: "crocodile", name: "Crocodile", icon: "🐊", packCode: "animal"},
	{code: "sauropod", name: "Sauropod", icon: "🦕", packCode: "animal"},
	{code: "trex", name: "T-Rex", icon: "🦖", packCode: "animal"},
	{code: "dragon", name: "Dragon", icon: "🐉", packCode: "animal"},
	{code: "whale", name: "Whale", icon: "🐳", packCode: "animal"},
	{code: "spouting_whale", name: "Spouting Whale", icon: "🐋", packCode: "animal"},
	{code: "dolphin", name: "Dolphin", icon: "🐬", packCode: "animal"},
	{code: "seal", name: "Seal", icon: "🦭", packCode: "animal"},
	{code: "fish", name: "Fish", icon: "🐟", packCode: "animal"},
	{code: "tropical_fish", name: "Tropical Fish", icon: "🐠", packCode: "animal"},
	{code: "blowfish", name: "Blowfish", icon: "🐡", packCode: "animal"},
	{code: "shark", name: "Shark", icon: "🦈", packCode: "animal"},
	{code: "octopus", name: "Octopus", icon: "🐙", packCode: "animal"},
	{code: "squid", name: "Squid", icon: "🦑", packCode: "animal"},
	{code: "crab", name: "Crab", icon: "🦀", packCode: "animal"},
	{code: "lobster", name: "Lobster", icon: "🦞", packCode: "animal"},
	{code: "shrimp", name: "Shrimp", icon: "🦐", packCode: "animal"},
	{code: "snail", name: "Snail", icon: "🐌", packCode: "animal"},
	{code: "butterfly", name: "Butterfly", icon: "🦋", packCode: "animal"},
	{code: "bug", name: "Bug", icon: "🐛", packCode: "animal"},
	{code: "ant", name: "Ant", icon: "🐜", packCode: "animal"},
	{code: "bee", name: "Honeybee", icon: "🐝", packCode: "animal"},
	{code: "beetle", name: "Beetle", icon: "🪲", packCode: "animal"},
	{code: "cricket", name: "Cricket", icon: "🦗", packCode: "animal"},
	{code: "cockroach", name: "Cockroach", icon: "🪳", packCode: "animal"},
	{code: "spider", name: "Spider", icon: "🕷️", packCode: "animal"},
	{code: "scorpion", name: "Scorpion", icon: "🦂", packCode: "animal"},
	{code: "mosquito", name: "Mosquito", icon: "🦟", packCode: "animal"},
	{code: "fly", name: "Fly", icon: "🪰", packCode: "animal"},
	{code: "worm", name: "Worm", icon: "🪱", packCode: "animal"},
}

var peopleData = []emojiDef{
	{code: "police_officer", name: "Police Officer", icon: "👮", packCode: "people"},
	{code: "detective", name: "Detective", icon: "🕵️", packCode: "people"},
	{code: "guard", name: "Guard", icon: "💂", packCode: "people"},
	{code: "construction_worker", name: "Construction Worker", icon: "👷", packCode: "people"},
	{code: "doctor_man", name: "Man Doctor", icon: "👨‍⚕️", packCode: "people"},
	{code: "doctor_woman", name: "Woman Doctor", icon: "👩‍⚕️", packCode: "people"},
	{code: "teacher_man", name: "Man Teacher", icon: "👨‍🏫", packCode: "people"},
	{code: "teacher_woman", name: "Woman Teacher", icon: "👩‍🏫", packCode: "people"},
	{code: "cook_man", name: "Man Cook", icon: "👨‍🍳", packCode: "people"},
	{code: "cook_woman", name: "Woman Cook", icon: "👩‍🍳", packCode: "people"},
	{code: "programmer_man", name: "Man Technologist", icon: "👨‍💻", packCode: "people"},
	{code: "programmer_woman", name: "Woman Technologist", icon: "👩‍💻", packCode: "people"},
	{code: "scientist_man", name: "Man Scientist", icon: "👨‍🔬", packCode: "people"},
	{code: "scientist_woman", name: "Woman Scientist", icon: "👩‍🔬", packCode: "people"},
	{code: "astronaut_man", name: "Man Astronaut", icon: "👨‍🚀", packCode: "people"},
	{code: "astronaut_woman", name: "Woman Astronaut", icon: "👩‍🚀", packCode: "people"},
	{code: "artist_man", name: "Man Artist", icon: "👨‍🎨", packCode: "people"},
	{code: "artist_woman", name: "Woman Artist", icon: "👩‍🎨", packCode: "people"},
	{code: "firefighter_man", name: "Man Firefighter", icon: "👨‍🚒", packCode: "people"},
	{code: "firefighter_woman", name: "Woman Firefighter", icon: "👩‍🚒", packCode: "people"},
	{code: "pilot_man", name: "Man Pilot", icon: "👨‍✈️", packCode: "people"},
	{code: "pilot_woman", name: "Woman Pilot", icon: "👩‍✈️", packCode: "people"},
	{code: "judge_man", name: "Man Judge", icon: "👨‍⚖️", packCode: "people"},
	{code: "judge_woman", name: "Woman Judge", icon: "👩‍⚖️", packCode: "people"},
	{code: "mechanic_man", name: "Man Mechanic", icon: "👨‍🔧", packCode: "people"},
	{code: "mechanic_woman", name: "Woman Mechanic", icon: "👩‍🔧", packCode: "people"},
	{code: "raising_hand", name: "Raising Hand", icon: "🙋", packCode: "people"},
	{code: "person_tipping_hand", name: "Person Tipping Hand", icon: "💁", packCode: "people"},
	{code: "person_bowing", name: "Person Bowing", icon: "🙇", packCode: "people"},
	{code: "person_facepalming", name: "Person Facepalming", icon: "🤦", packCode: "people"},
	{code: "person_shrugging", name: "Person Shrugging", icon: "🤷", packCode: "people"},
	{code: "person_no", name: "Person Gesturing No", icon: "🙅", packCode: "people"},
	{code: "person_ok", name: "Person Gesturing OK", icon: "🙆", packCode: "people"},
	{code: "person_pouting", name: "Person Pouting", icon: "🙎", packCode: "people"},
	{code: "person_frowning", name: "Person Frowning", icon: "🙍", packCode: "people"},
	{code: "person_running", name: "Person Running", icon: "🏃", packCode: "people"},
	{code: "person_walking", name: "Person Walking", icon: "🚶", packCode: "people"},
	{code: "person_standing", name: "Person Standing", icon: "🧍", packCode: "people"},
	{code: "person_kneeling", name: "Person Kneeling", icon: "🧎", packCode: "people"},
	{code: "person_dancing", name: "Woman Dancing", icon: "💃", packCode: "people"},
	{code: "man_dancing", name: "Man Dancing", icon: "🕺", packCode: "people"},
	{code: "people_holding_hands", name: "People Holding Hands", icon: "🧑‍🤝‍🧑", packCode: "people"},
	{code: "family", name: "Family", icon: "👪", packCode: "people"},
	{code: "couple_with_heart", name: "Couple With Heart", icon: "💑", packCode: "people"},
	{code: "kiss", name: "Kiss", icon: "💏", packCode: "people"},
	{code: "family_man_woman_boy", name: "Family MWB", icon: "👨‍👩‍👦", packCode: "people"},
	{code: "family_man_woman_girl", name: "Family MWG", icon: "👨‍👩‍👧", packCode: "people"},
	{code: "family_man_woman_boy_boy", name: "Family MWBB", icon: "👨‍👩‍👦‍👦", packCode: "people"},
	{code: "family_man_woman_girl_girl", name: "Family MWGG", icon: "👨‍👩‍👧‍👧", packCode: "people"},
	{code: "ear", name: "Ear", icon: "👂", packCode: "people"},
	{code: "nose", name: "Nose", icon: "👃", packCode: "people"},
	{code: "brain", name: "Brain", icon: "🧠", packCode: "people"},
	{code: "eye", name: "Eye", icon: "👁️", packCode: "people"},
	{code: "eyes", name: "Eyes", icon: "👀", packCode: "people"},
	{code: "mouth", name: "Mouth", icon: "👄", packCode: "people"},
	{code: "tongue", name: "Tongue", icon: "👅", packCode: "people"},
	{code: "arm", name: "Arm", icon: "💪", packCode: "people"},
	{code: "mechanical_arm", name: "Mechanical Arm", icon: "🦾", packCode: "people"},
	{code: "leg", name: "Leg", icon: "🦵", packCode: "people"},
	{code: "foot", name: "Foot", icon: "🦶", packCode: "people"},
	{code: "bone", name: "Bone", icon: "🦴", packCode: "people"},
	{code: "tooth", name: "Tooth", icon: "🦷", packCode: "people"},
	{code: "anatomical_heart", name: "Anatomical Heart", icon: "🫀", packCode: "people"},
	{code: "lungs", name: "Lungs", icon: "🫁", packCode: "people"},
}

var foodData = []emojiDef{
	{code: "green_apple", name: "Green Apple", icon: "🍏", packCode: "food"},
	{code: "red_apple", name: "Red Apple", icon: "🍎", packCode: "food"},
	{code: "pear", name: "Pear", icon: "🍐", packCode: "food"},
	{code: "tangerine", name: "Tangerine", icon: "🍊", packCode: "food"},
	{code: "lemon", name: "Lemon", icon: "🍋", packCode: "food"},
	{code: "banana", name: "Banana", icon: "🍌", packCode: "food"},
	{code: "watermelon", name: "Watermelon", icon: "🍉", packCode: "food"},
	{code: "grapes", name: "Grapes", icon: "🍇", packCode: "food"},
	{code: "strawberry", name: "Strawberry", icon: "🍓", packCode: "food"},
	{code: "blueberries", name: "Blueberries", icon: "🫐", packCode: "food"},
	{code: "melon", name: "Melon", icon: "🍈", packCode: "food"},
	{code: "cherries", name: "Cherries", icon: "🍒", packCode: "food"},
	{code: "peach", name: "Peach", icon: "🍑", packCode: "food"},
	{code: "mango", name: "Mango", icon: "🥭", packCode: "food"},
	{code: "pineapple", name: "Pineapple", icon: "🍍", packCode: "food"},
	{code: "coconut", name: "Coconut", icon: "🥥", packCode: "food"},
	{code: "kiwi", name: "Kiwi", icon: "🥝", packCode: "food"},
	{code: "avocado", name: "Avocado", icon: "🥑", packCode: "food"},
	{code: "eggplant", name: "Eggplant", icon: "🍆", packCode: "food"},
	{code: "potato", name: "Potato", icon: "🥔", packCode: "food"},
	{code: "carrot", name: "Carrot", icon: "🥕", packCode: "food"},
	{code: "corn", name: "Corn", icon: "🌽", packCode: "food"},
	{code: "hot_pepper", name: "Hot Pepper", icon: "🌶️", packCode: "food"},
	{code: "cucumber", name: "Cucumber", icon: "🥒", packCode: "food"},
	{code: "leafy_green", name: "Leafy Green", icon: "🥬", packCode: "food"},
	{code: "broccoli", name: "Broccoli", icon: "🥦", packCode: "food"},
	{code: "garlic", name: "Garlic", icon: "🧄", packCode: "food"},
	{code: "onion", name: "Onion", icon: "🧅", packCode: "food"},
	{code: "bread", name: "Bread", icon: "🍞", packCode: "food"},
	{code: "croissant", name: "Croissant", icon: "🥐", packCode: "food"},
	{code: "baguette", name: "Baguette", icon: "🥖", packCode: "food"},
	{code: "pretzel", name: "Pretzel", icon: "🥨", packCode: "food"},
	{code: "pancakes", name: "Pancakes", icon: "🥞", packCode: "food"},
	{code: "waffle", name: "Waffle", icon: "🧇", packCode: "food"},
	{code: "cheese", name: "Cheese", icon: "🧀", packCode: "food"},
	{code: "meat_on_bone", name: "Meat On Bone", icon: "🍖", packCode: "food"},
	{code: "poultry_leg", name: "Poultry Leg", icon: "🍗", packCode: "food"},
	{code: "bacon", name: "Bacon", icon: "🥓", packCode: "food"},
	{code: "hamburger", name: "Hamburger", icon: "🍔", packCode: "food"},
	{code: "fries", name: "French Fries", icon: "🍟", packCode: "food"},
	{code: "pizza", name: "Pizza", icon: "🍕", packCode: "food"},
	{code: "hotdog", name: "Hot Dog", icon: "🌭", packCode: "food"},
	{code: "sandwich", name: "Sandwich", icon: "🥪", packCode: "food"},
	{code: "taco", name: "Taco", icon: "🌮", packCode: "food"},
	{code: "burrito", name: "Burrito", icon: "🌯", packCode: "food"},
	{code: "spaghetti", name: "Spaghetti", icon: "🍝", packCode: "food"},
	{code: "ramen", name: "Ramen", icon: "🍜", packCode: "food"},
	{code: "sushi", name: "Sushi", icon: "🍣", packCode: "food"},
	{code: "fried_shrimp", name: "Fried Shrimp", icon: "🍤", packCode: "food"},
	{code: "ice_cream", name: "Ice Cream", icon: "🍨", packCode: "food"},
	{code: "soft_ice_cream", name: "Soft Ice Cream", icon: "🍦", packCode: "food"},
	{code: "cake", name: "Cake", icon: "🍰", packCode: "food"},
	{code: "birthday_cake", name: "Birthday Cake", icon: "🎂", packCode: "food"},
	{code: "cupcake", name: "Cupcake", icon: "🧁", packCode: "food"},
	{code: "donut", name: "Donut", icon: "🍩", packCode: "food"},
	{code: "cookie", name: "Cookie", icon: "🍪", packCode: "food"},
	{code: "chocolate", name: "Chocolate", icon: "🍫", packCode: "food"},
	{code: "candy", name: "Candy", icon: "🍬", packCode: "food"},
	{code: "lollipop", name: "Lollipop", icon: "🍭", packCode: "food"},
	{code: "coffee", name: "Hot Beverage", icon: "☕", packCode: "food"},
	{code: "tea", name: "Teacup", icon: "🍵", packCode: "food"},
	{code: "bubble_tea", name: "Bubble Tea", icon: "🧋", packCode: "food"},
	{code: "juice", name: "Juice Box", icon: "🧃", packCode: "food"},
	{code: "cup_with_straw", name: "Cup With Straw", icon: "🥤", packCode: "food"},
	{code: "milk", name: "Glass Of Milk", icon: "🥛", packCode: "food"},
}

var natureData = []emojiDef{
	{code: "evergreen_tree", name: "Evergreen Tree", icon: "🌲", packCode: "nature"},
	{code: "deciduous_tree", name: "Deciduous Tree", icon: "🌳", packCode: "nature"},
	{code: "palm_tree", name: "Palm Tree", icon: "🌴", packCode: "nature"},
	{code: "cactus", name: "Cactus", icon: "🌵", packCode: "nature"},
	{code: "seedling", name: "Seedling", icon: "🌱", packCode: "nature"},
	{code: "herb", name: "Herb", icon: "🌿", packCode: "nature"},
	{code: "shamrock", name: "Shamrock", icon: "☘️", packCode: "nature"},
	{code: "four_leaf_clover", name: "Four Leaf Clover", icon: "🍀", packCode: "nature"},
	{code: "maple_leaf", name: "Maple Leaf", icon: "🍁", packCode: "nature"},
	{code: "fallen_leaf", name: "Fallen Leaf", icon: "🍂", packCode: "nature"},
	{code: "leaf_fluttering", name: "Leaf Fluttering", icon: "🍃", packCode: "nature"},
	{code: "rose", name: "Rose", icon: "🌹", packCode: "nature"},
	{code: "wilted_flower", name: "Wilted Flower", icon: "🥀", packCode: "nature"},
	{code: "hibiscus", name: "Hibiscus", icon: "🌺", packCode: "nature"},
	{code: "sunflower", name: "Sunflower", icon: "🌻", packCode: "nature"},
	{code: "blossom", name: "Blossom", icon: "🌼", packCode: "nature"},
	{code: "tulip", name: "Tulip", icon: "🌷", packCode: "nature"},
	{code: "cherry_blossom", name: "Cherry Blossom", icon: "🌸", packCode: "nature"},
	{code: "lotus", name: "Lotus", icon: "🪷", packCode: "nature"},
	{code: "hyacinth", name: "Hyacinth", icon: "🪻", packCode: "nature"},
	{code: "ear_of_rice", name: "Ear Of Rice", icon: "🌾", packCode: "nature"},
	{code: "mushroom", name: "Mushroom", icon: "🍄", packCode: "nature"},
	{code: "chestnut", name: "Chestnut", icon: "🌰", packCode: "nature"},
	{code: "sun", name: "Sun", icon: "☀️", packCode: "nature"},
	{code: "sun_behind_cloud", name: "Sun Behind Cloud", icon: "⛅", packCode: "nature"},
	{code: "sun_small_cloud", name: "Sun Behind Small Cloud", icon: "🌤️", packCode: "nature"},
	{code: "sun_large_cloud", name: "Sun Behind Large Cloud", icon: "🌥️", packCode: "nature"},
	{code: "sun_rain_cloud", name: "Sun Behind Rain Cloud", icon: "🌦️", packCode: "nature"},
	{code: "cloud", name: "Cloud", icon: "☁️", packCode: "nature"},
	{code: "rain_cloud", name: "Cloud With Rain", icon: "🌧️", packCode: "nature"},
	{code: "thunder_cloud", name: "Cloud With Lightning", icon: "🌩️", packCode: "nature"},
	{code: "storm_cloud", name: "Cloud With Lightning And Rain", icon: "⛈️", packCode: "nature"},
	{code: "snow_cloud", name: "Cloud With Snow", icon: "🌨️", packCode: "nature"},
	{code: "snowflake", name: "Snowflake", icon: "❄️", packCode: "nature"},
	{code: "snowman", name: "Snowman", icon: "☃️", packCode: "nature"},
	{code: "wind_face", name: "Wind Face", icon: "🌬️", packCode: "nature"},
	{code: "tornado", name: "Tornado", icon: "🌪️", packCode: "nature"},
	{code: "rainbow", name: "Rainbow", icon: "🌈", packCode: "nature"},
	{code: "droplet", name: "Droplet", icon: "💧", packCode: "nature"},
	{code: "water_wave", name: "Water Wave", icon: "🌊", packCode: "nature"},
	{code: "new_moon", name: "New Moon", icon: "🌑", packCode: "nature"},
	{code: "waxing_crescent_moon", name: "Waxing Crescent Moon", icon: "🌒", packCode: "nature"},
	{code: "first_quarter_moon", name: "First Quarter Moon", icon: "🌓", packCode: "nature"},
	{code: "waxing_gibbous_moon", name: "Waxing Gibbous Moon", icon: "🌔", packCode: "nature"},
	{code: "full_moon", name: "Full Moon", icon: "🌕", packCode: "nature"},
	{code: "waning_gibbous_moon", name: "Waning Gibbous Moon", icon: "🌖", packCode: "nature"},
	{code: "last_quarter_moon", name: "Last Quarter Moon", icon: "🌗", packCode: "nature"},
	{code: "waning_crescent_moon", name: "Waning Crescent Moon", icon: "🌘", packCode: "nature"},
	{code: "crescent_moon", name: "Crescent Moon", icon: "🌙", packCode: "nature"},
	{code: "star", name: "Star", icon: "⭐", packCode: "nature"},
	{code: "glowing_star", name: "Glowing Star", icon: "🌟", packCode: "nature"},
	{code: "sparkles", name: "Sparkles", icon: "✨", packCode: "nature"},
	{code: "comet", name: "Comet", icon: "☄️", packCode: "nature"},
	{code: "sun_with_face", name: "Sun With Face", icon: "🌞", packCode: "nature"},
	{code: "full_moon_face", name: "Full Moon Face", icon: "🌝", packCode: "nature"},
	{code: "new_moon_face", name: "New Moon Face", icon: "🌚", packCode: "nature"},
	{code: "fire", name: "Fire", icon: "🔥", packCode: "nature"},
	{code: "volcano", name: "Volcano", icon: "🌋", packCode: "nature"},
	{code: "mountain", name: "Mountain", icon: "⛰️", packCode: "nature"},
	{code: "snow_capped_mountain", name: "Snow Capped Mountain", icon: "🏔️", packCode: "nature"},
	{code: "camping", name: "Camping", icon: "🏕️", packCode: "nature"},
	{code: "national_park", name: "National Park", icon: "🏞️", packCode: "nature"},
}

var travelData = []emojiDef{
	{code: "automobile", name: "Automobile", icon: "🚗", packCode: "travel"},
	{code: "taxi", name: "Taxi", icon: "🚕", packCode: "travel"},
	{code: "sport_utility_vehicle", name: "SUV", icon: "🚙", packCode: "travel"},
	{code: "bus", name: "Bus", icon: "🚌", packCode: "travel"},
	{code: "trolleybus", name: "Trolleybus", icon: "🚎", packCode: "travel"},
	{code: "racing_car", name: "Racing Car", icon: "🏎️", packCode: "travel"},
	{code: "police_car", name: "Police Car", icon: "🚓", packCode: "travel"},
	{code: "ambulance", name: "Ambulance", icon: "🚑", packCode: "travel"},
	{code: "fire_engine", name: "Fire Engine", icon: "🚒", packCode: "travel"},
	{code: "delivery_truck", name: "Delivery Truck", icon: "🚚", packCode: "travel"},
	{code: "articulated_lorry", name: "Articulated Lorry", icon: "🚛", packCode: "travel"},
	{code: "tractor", name: "Tractor", icon: "🚜", packCode: "travel"},
	{code: "motorcycle", name: "Motorcycle", icon: "🏍️", packCode: "travel"},
	{code: "motor_scooter", name: "Motor Scooter", icon: "🛵", packCode: "travel"},
	{code: "bicycle", name: "Bicycle", icon: "🚲", packCode: "travel"},
	{code: "kick_scooter", name: "Kick Scooter", icon: "🛴", packCode: "travel"},
	{code: "roller_skate", name: "Roller Skate", icon: "🛼", packCode: "travel"},
	{code: "fuel_pump", name: "Fuel Pump", icon: "⛽", packCode: "travel"},
	{code: "traffic_light", name: "Traffic Light", icon: "🚦", packCode: "travel"},
	{code: "construction", name: "Construction", icon: "🚧", packCode: "travel"},
	{code: "airplane", name: "Airplane", icon: "✈️", packCode: "travel"},
	{code: "airplane_departure", name: "Airplane Departure", icon: "🛫", packCode: "travel"},
	{code: "airplane_arrival", name: "Airplane Arrival", icon: "🛬", packCode: "travel"},
	{code: "small_airplane", name: "Small Airplane", icon: "🛩️", packCode: "travel"},
	{code: "helicopter", name: "Helicopter", icon: "🚁", packCode: "travel"},
	{code: "rocket", name: "Rocket", icon: "🚀", packCode: "travel"},
	{code: "satellite", name: "Satellite", icon: "🛰️", packCode: "travel"},
	{code: "flying_saucer", name: "Flying Saucer", icon: "🛸", packCode: "travel"},
	{code: "canoe", name: "Canoe", icon: "🛶", packCode: "travel"},
	{code: "sailboat", name: "Sailboat", icon: "⛵", packCode: "travel"},
	{code: "speedboat", name: "Speedboat", icon: "🚤", packCode: "travel"},
	{code: "ferry", name: "Ferry", icon: "⛴️", packCode: "travel"},
	{code: "ship", name: "Ship", icon: "🚢", packCode: "travel"},
	{code: "anchor", name: "Anchor", icon: "⚓", packCode: "travel"},
	{code: "compass", name: "Compass", icon: "🧭", packCode: "travel"},
	{code: "world_map", name: "World Map", icon: "🗺️", packCode: "travel"},
	{code: "house", name: "House", icon: "🏠", packCode: "travel"},
	{code: "house_with_garden", name: "House With Garden", icon: "🏡", packCode: "travel"},
	{code: "office_building", name: "Office Building", icon: "🏢", packCode: "travel"},
	{code: "post_office", name: "Post Office", icon: "🏣", packCode: "travel"},
	{code: "hospital", name: "Hospital", icon: "🏥", packCode: "travel"},
	{code: "bank", name: "Bank", icon: "🏦", packCode: "travel"},
	{code: "hotel", name: "Hotel", icon: "🏨", packCode: "travel"},
	{code: "school", name: "School", icon: "🏫", packCode: "travel"},
	{code: "factory", name: "Factory", icon: "🏭", packCode: "travel"},
	{code: "castle", name: "Castle", icon: "🏰", packCode: "travel"},
	{code: "japanese_castle", name: "Japanese Castle", icon: "🏯", packCode: "travel"},
	{code: "stadium", name: "Stadium", icon: "🏟️", packCode: "travel"},
	{code: "ferris_wheel", name: "Ferris Wheel", icon: "🎡", packCode: "travel"},
	{code: "roller_coaster", name: "Roller Coaster", icon: "🎢", packCode: "travel"},
	{code: "carousel_horse", name: "Carousel Horse", icon: "🎠", packCode: "travel"},
	{code: "statue_of_liberty", name: "Statue Of Liberty", icon: "🗽", packCode: "travel"},
	{code: "tokyo_tower", name: "Tokyo Tower", icon: "🗼", packCode: "travel"},
	{code: "beach_with_umbrella", name: "Beach With Umbrella", icon: "🏖️", packCode: "travel"},
	{code: "desert", name: "Desert", icon: "🏜️", packCode: "travel"},
	{code: "desert_island", name: "Desert Island", icon: "🏝️", packCode: "travel"},
	{code: "mount_fuji", name: "Mount Fuji", icon: "🗻", packCode: "travel"},
	{code: "travel_mountain", name: "Mountain", icon: "⛰️", packCode: "travel"},
	{code: "travel_snow_mountain", name: "Snow Mountain", icon: "🏔️", packCode: "travel"},
	{code: "sunrise", name: "Sunrise", icon: "🌅", packCode: "travel"},
	{code: "sunrise_over_mountains", name: "Sunrise Over Mountains", icon: "🌄", packCode: "travel"},
	{code: "cityscape", name: "Cityscape", icon: "🏙️", packCode: "travel"},
	{code: "night_with_stars", name: "Night With Stars", icon: "🌃", packCode: "travel"},
	{code: "bridge_at_night", name: "Bridge At Night", icon: "🌉", packCode: "travel"},
	{code: "church", name: "Church", icon: "⛪", packCode: "travel"},
	{code: "mosque", name: "Mosque", icon: "🕌", packCode: "travel"},
	{code: "hindu_temple", name: "Hindu Temple", icon: "🛕", packCode: "travel"},
	{code: "synagogue", name: "Synagogue", icon: "🕍", packCode: "travel"},
	{code: "fountain", name: "Fountain", icon: "⛲", packCode: "travel"},
	{code: "tent", name: "Tent", icon: "⛺", packCode: "travel"},
	{code: "travel_camping", name: "Camping", icon: "🏕️", packCode: "travel"},
}

var activityData = []emojiDef{
	{code: "soccer_ball", name: "Soccer Ball", icon: "⚽", packCode: "activity"},
	{code: "basketball", name: "Basketball", icon: "🏀", packCode: "activity"},
	{code: "american_football", name: "American Football", icon: "🏈", packCode: "activity"},
	{code: "baseball", name: "Baseball", icon: "⚾", packCode: "activity"},
	{code: "softball", name: "Softball", icon: "🥎", packCode: "activity"},
	{code: "tennis", name: "Tennis", icon: "🎾", packCode: "activity"},
	{code: "volleyball", name: "Volleyball", icon: "🏐", packCode: "activity"},
	{code: "rugby", name: "Rugby Football", icon: "🏉", packCode: "activity"},
	{code: "flying_disc", name: "Flying Disc", icon: "🥏", packCode: "activity"},
	{code: "bowling", name: "Bowling", icon: "🎳", packCode: "activity"},
	{code: "billiards", name: "Pool 8 Ball", icon: "🎱", packCode: "activity"},
	{code: "ping_pong", name: "Ping Pong", icon: "🏓", packCode: "activity"},
	{code: "badminton", name: "Badminton", icon: "🏸", packCode: "activity"},
	{code: "hockey_stick", name: "Field Hockey", icon: "🏑", packCode: "activity"},
	{code: "ice_hockey", name: "Ice Hockey", icon: "🏒", packCode: "activity"},
	{code: "lacrosse", name: "Lacrosse", icon: "🥍", packCode: "activity"},
	{code: "cricket", name: "Cricket", icon: "🏏", packCode: "activity"},
	{code: "boxing_glove", name: "Boxing Glove", icon: "🥊", packCode: "activity"},
	{code: "martial_arts", name: "Martial Arts Uniform", icon: "🥋", packCode: "activity"},
	{code: "goal_net", name: "Goal Net", icon: "🥅", packCode: "activity"},
	{code: "flag_hole", name: "Flag In Hole", icon: "⛳", packCode: "activity"},
	{code: "ice_skate", name: "Ice Skate", icon: "⛸️", packCode: "activity"},
	{code: "fishing_pole", name: "Fishing Pole", icon: "🎣", packCode: "activity"},
	{code: "running_shirt", name: "Running Shirt", icon: "🎽", packCode: "activity"},
	{code: "ski", name: "Skis", icon: "🎿", packCode: "activity"},
	{code: "sled", name: "Sled", icon: "🛷", packCode: "activity"},
	{code: "curling_stone", name: "Curling Stone", icon: "🥌", packCode: "activity"},
	{code: "video_game", name: "Video Game", icon: "🎮", packCode: "activity"},
	{code: "joystick", name: "Joystick", icon: "🕹️", packCode: "activity"},
	{code: "slot_machine", name: "Slot Machine", icon: "🎰", packCode: "activity"},
	{code: "game_die", name: "Game Die", icon: "🎲", packCode: "activity"},
	{code: "puzzle_piece", name: "Puzzle Piece", icon: "🧩", packCode: "activity"},
	{code: "chess_pawn", name: "Chess Pawn", icon: "♟️", packCode: "activity"},
	{code: "dart", name: "Direct Hit", icon: "🎯", packCode: "activity"},
	{code: "performing_arts", name: "Performing Arts", icon: "🎭", packCode: "activity"},
	{code: "artist_palette", name: "Artist Palette", icon: "🎨", packCode: "activity"},
	{code: "clapper_board", name: "Clapper Board", icon: "🎬", packCode: "activity"},
	{code: "film_frames", name: "Film Frames", icon: "🎞️", packCode: "activity"},
	{code: "microphone", name: "Microphone", icon: "🎤", packCode: "activity"},
	{code: "headphone", name: "Headphone", icon: "🎧", packCode: "activity"},
	{code: "musical_score", name: "Musical Score", icon: "🎼", packCode: "activity"},
	{code: "musical_note", name: "Musical Note", icon: "🎵", packCode: "activity"},
	{code: "multiple_notes", name: "Multiple Musical Notes", icon: "🎶", packCode: "activity"},
	{code: "piano", name: "Musical Keyboard", icon: "🎹", packCode: "activity"},
	{code: "drum", name: "Drum", icon: "🥁", packCode: "activity"},
	{code: "guitar", name: "Guitar", icon: "🎸", packCode: "activity"},
	{code: "violin", name: "Violin", icon: "🎻", packCode: "activity"},
	{code: "trumpet", name: "Trumpet", icon: "🎺", packCode: "activity"},
	{code: "saxophone", name: "Saxophone", icon: "🎷", packCode: "activity"},
	{code: "accordion", name: "Accordion", icon: "🪗", packCode: "activity"},
	{code: "ticket", name: "Ticket", icon: "🎫", packCode: "activity"},
	{code: "admission_tickets", name: "Admission Tickets", icon: "🎟️", packCode: "activity"},
	{code: "circus_tent", name: "Circus Tent", icon: "🎪", packCode: "activity"},
	{code: "trophy", name: "Trophy", icon: "🏆", packCode: "activity"},
	{code: "sports_medal", name: "Sports Medal", icon: "🏅", packCode: "activity"},
	{code: "first_place_medal", name: "First Place Medal", icon: "🥇", packCode: "activity"},
	{code: "second_place_medal", name: "Second Place Medal", icon: "🥈", packCode: "activity"},
	{code: "third_place_medal", name: "Third Place Medal", icon: "🥉", packCode: "activity"},
	{code: "reminder_ribbon", name: "Reminder Ribbon", icon: "🎗️", packCode: "activity"},
	{code: "rosette", name: "Rosette", icon: "🏵️", packCode: "activity"},
}

var objectData = []emojiDef{
	{code: "mobile_phone", name: "Mobile Phone", icon: "📱", packCode: "object"},
	{code: "mobile_phone_arrow", name: "Mobile Phone With Arrow", icon: "📲", packCode: "object"},
	{code: "telephone", name: "Telephone", icon: "☎️", packCode: "object"},
	{code: "telephone_receiver", name: "Telephone Receiver", icon: "📞", packCode: "object"},
	{code: "pager", name: "Pager", icon: "📟", packCode: "object"},
	{code: "fax_machine", name: "Fax Machine", icon: "📠", packCode: "object"},
	{code: "laptop", name: "Laptop", icon: "💻", packCode: "object"},
	{code: "desktop_computer", name: "Desktop Computer", icon: "🖥️", packCode: "object"},
	{code: "printer", name: "Printer", icon: "🖨️", packCode: "object"},
	{code: "keyboard", name: "Keyboard", icon: "⌨️", packCode: "object"},
	{code: "computer_mouse", name: "Computer Mouse", icon: "🖱️", packCode: "object"},
	{code: "trackball", name: "Trackball", icon: "🖲️", packCode: "object"},
	{code: "floppy_disk", name: "Floppy Disk", icon: "💾", packCode: "object"},
	{code: "optical_disk", name: "Optical Disk", icon: "💿", packCode: "object"},
	{code: "dvd", name: "DVD", icon: "📀", packCode: "object"},
	{code: "camera", name: "Camera", icon: "📷", packCode: "object"},
	{code: "camera_flash", name: "Camera With Flash", icon: "📸", packCode: "object"},
	{code: "video_camera", name: "Video Camera", icon: "📹", packCode: "object"},
	{code: "movie_camera", name: "Movie Camera", icon: "🎥", packCode: "object"},
	{code: "film_projector", name: "Film Projector", icon: "📽️", packCode: "object"},
	{code: "television", name: "Television", icon: "📺", packCode: "object"},
	{code: "radio", name: "Radio", icon: "📻", packCode: "object"},
	{code: "obj_microphone", name: "Microphone", icon: "🎤", packCode: "object"},
	{code: "studio_microphone", name: "Studio Microphone", icon: "🎙️", packCode: "object"},
	{code: "obj_headphone", name: "Headphone", icon: "🎧", packCode: "object"},
	{code: "speaker", name: "Speaker", icon: "🔈", packCode: "object"},
	{code: "speaker_medium", name: "Speaker Medium", icon: "🔉", packCode: "object"},
	{code: "speaker_high", name: "Speaker High", icon: "🔊", packCode: "object"},
	{code: "mute", name: "Muted Speaker", icon: "🔇", packCode: "object"},
	{code: "battery", name: "Battery", icon: "🔋", packCode: "object"},
	{code: "electric_plug", name: "Electric Plug", icon: "🔌", packCode: "object"},
	{code: "light_bulb", name: "Light Bulb", icon: "💡", packCode: "object"},
	{code: "flashlight", name: "Flashlight", icon: "🔦", packCode: "object"},
	{code: "candle", name: "Candle", icon: "🕯️", packCode: "object"},
	{code: "mailbox", name: "Mailbox", icon: "📫", packCode: "object"},
	{code: "incoming_envelope", name: "Incoming Envelope", icon: "📨", packCode: "object"},
	{code: "envelope", name: "Envelope", icon: "✉️", packCode: "object"},
	{code: "email", name: "Email", icon: "📧", packCode: "object"},
	{code: "outbox_tray", name: "Outbox Tray", icon: "📤", packCode: "object"},
	{code: "inbox_tray", name: "Inbox Tray", icon: "📥", packCode: "object"},
	{code: "memo", name: "Memo", icon: "📝", packCode: "object"},
	{code: "page_facing_up", name: "Page Facing Up", icon: "📄", packCode: "object"},
	{code: "bookmark", name: "Bookmark", icon: "🔖", packCode: "object"},
	{code: "closed_book", name: "Closed Book", icon: "📕", packCode: "object"},
	{code: "green_book", name: "Green Book", icon: "📗", packCode: "object"},
	{code: "blue_book", name: "Blue Book", icon: "📘", packCode: "object"},
	{code: "orange_book", name: "Orange Book", icon: "📙", packCode: "object"},
	{code: "books", name: "Books", icon: "📚", packCode: "object"},
	{code: "newspaper", name: "Newspaper", icon: "📰", packCode: "object"},
	{code: "rolled_up_newspaper", name: "Rolled Up Newspaper", icon: "🗞️", packCode: "object"},
	{code: "calendar", name: "Calendar", icon: "📅", packCode: "object"},
	{code: "tear_off_calendar", name: "Tear Off Calendar", icon: "📆", packCode: "object"},
	{code: "pushpin", name: "Pushpin", icon: "📌", packCode: "object"},
	{code: "round_pushpin", name: "Round Pushpin", icon: "📍", packCode: "object"},
	{code: "paperclip", name: "Paperclip", icon: "📎", packCode: "object"},
	{code: "linked_paperclips", name: "Linked Paperclips", icon: "🖇️", packCode: "object"},
	{code: "straight_ruler", name: "Straight Ruler", icon: "📏", packCode: "object"},
	{code: "triangular_ruler", name: "Triangular Ruler", icon: "📐", packCode: "object"},
	{code: "scissors", name: "Scissors", icon: "✂️", packCode: "object"},
	{code: "pen", name: "Pen", icon: "🖊️", packCode: "object"},
	{code: "fountain_pen", name: "Fountain Pen", icon: "🖋️", packCode: "object"},
	{code: "paintbrush", name: "Paintbrush", icon: "🖌️", packCode: "object"},
	{code: "crayon", name: "Crayon", icon: "🖍️", packCode: "object"},
	{code: "money_bag", name: "Money Bag", icon: "💰", packCode: "object"},
	{code: "coin", name: "Coin", icon: "🪙", packCode: "object"},
	{code: "dollar_banknote", name: "Dollar Banknote", icon: "💵", packCode: "object"},
	{code: "yen_banknote", name: "Yen Banknote", icon: "💴", packCode: "object"},
	{code: "euro_banknote", name: "Euro Banknote", icon: "💶", packCode: "object"},
	{code: "pound_banknote", name: "Pound Banknote", icon: "💷", packCode: "object"},
	{code: "credit_card", name: "Credit Card", icon: "💳", packCode: "object"},
	{code: "receipt", name: "Receipt", icon: "🧾", packCode: "object"},
	{code: "toolbox", name: "Toolbox", icon: "🧰", packCode: "object"},
	{code: "hammer", name: "Hammer", icon: "🔨", packCode: "object"},
	{code: "axe", name: "Axe", icon: "🪓", packCode: "object"},
	{code: "pick", name: "Pick", icon: "⛏️", packCode: "object"},
	{code: "hammer_pick", name: "Hammer And Pick", icon: "⚒️", packCode: "object"},
	{code: "hammer_wrench", name: "Hammer And Wrench", icon: "🛠️", packCode: "object"},
	{code: "dagger", name: "Dagger", icon: "🗡️", packCode: "object"},
	{code: "shield", name: "Shield", icon: "🛡️", packCode: "object"},
	{code: "wrench", name: "Wrench", icon: "🔧", packCode: "object"},
	{code: "nut_and_bolt", name: "Nut And Bolt", icon: "🔩", packCode: "object"},
	{code: "gear", name: "Gear", icon: "⚙️", packCode: "object"},
	{code: "clamp", name: "Clamp", icon: "🗜️", packCode: "object"},
	{code: "test_tube", name: "Test Tube", icon: "🧪", packCode: "object"},
	{code: "petri_dish", name: "Petri Dish", icon: "🧫", packCode: "object"},
	{code: "dna", name: "DNA", icon: "🧬", packCode: "object"},
	{code: "microscope", name: "Microscope", icon: "🔬", packCode: "object"},
	{code: "telescope", name: "Telescope", icon: "🔭", packCode: "object"},
	{code: "satellite_antenna", name: "Satellite Antenna", icon: "📡", packCode: "object"},
	{code: "pill", name: "Pill", icon: "💊", packCode: "object"},
	{code: "syringe", name: "Syringe", icon: "💉", packCode: "object"},
	{code: "drop_of_blood", name: "Drop Of Blood", icon: "🩸", packCode: "object"},
	{code: "stethoscope", name: "Stethoscope", icon: "🩺", packCode: "object"},
	{code: "adhesive_bandage", name: "Adhesive Bandage", icon: "🩹", packCode: "object"},
	{code: "door", name: "Door", icon: "🚪", packCode: "object"},
	{code: "bed", name: "Bed", icon: "🛏️", packCode: "object"},
	{code: "couch", name: "Couch", icon: "🛋️", packCode: "object"},
	{code: "chair", name: "Chair", icon: "🪑", packCode: "object"},
	{code: "toilet", name: "Toilet", icon: "🚽", packCode: "object"},
	{code: "shower", name: "Shower", icon: "🚿", packCode: "object"},
	{code: "bathtub", name: "Bathtub", icon: "🛁", packCode: "object"},
	{code: "mirror", name: "Mirror", icon: "🪞", packCode: "object"},
	{code: "broom", name: "Broom", icon: "🧹", packCode: "object"},
	{code: "basket", name: "Basket", icon: "🧺", packCode: "object"},
	{code: "bucket", name: "Bucket", icon: "🪣", packCode: "object"},
	{code: "soap", name: "Soap", icon: "🧼", packCode: "object"},
	{code: "sponge", name: "Sponge", icon: "🧽", packCode: "object"},
	{code: "teddy_bear", name: "Teddy Bear", icon: "🧸", packCode: "object"},
	{code: "yo_yo", name: "Yo-Yo", icon: "🪀", packCode: "object"},
	{code: "kite", name: "Kite", icon: "🪁", packCode: "object"},
	{code: "eyeglasses", name: "Eyeglasses", icon: "👓", packCode: "object"},
	{code: "sunglasses", name: "Sunglasses", icon: "🕶️", packCode: "object"},
	{code: "lab_coat", name: "Lab Coat", icon: "🥼", packCode: "object"},
	{code: "safety_vest", name: "Safety Vest", icon: "🦺", packCode: "object"},
	{code: "tshirt", name: "T-Shirt", icon: "👕", packCode: "object"},
	{code: "jeans", name: "Jeans", icon: "👖", packCode: "object"},
	{code: "dress", name: "Dress", icon: "👗", packCode: "object"},
	{code: "kimono", name: "Kimono", icon: "👘", packCode: "object"},
	{code: "sari", name: "Sari", icon: "🥻", packCode: "object"},
	{code: "shorts", name: "Shorts", icon: "🩳", packCode: "object"},
	{code: "briefs", name: "Briefs", icon: "🩲", packCode: "object"},
	{code: "shoe", name: "Shoe", icon: "👞", packCode: "object"},
	{code: "running_shoe", name: "Running Shoe", icon: "👟", packCode: "object"},
	{code: "hiking_boot", name: "Hiking Boot", icon: "🥾", packCode: "object"},
	{code: "sandal", name: "Sandal", icon: "👡", packCode: "object"},
	{code: "ring", name: "Ring", icon: "💍", packCode: "object"},
	{code: "gem_stone", name: "Gem Stone", icon: "💎", packCode: "object"},
	{code: "crown", name: "Crown", icon: "👑", packCode: "object"},
	{code: "key", name: "Key", icon: "🔑", packCode: "object"},
	{code: "old_key", name: "Old Key", icon: "🗝️", packCode: "object"},
	{code: "locked", name: "Locked", icon: "🔒", packCode: "object"},
	{code: "unlocked", name: "Unlocked", icon: "🔓", packCode: "object"},
	{code: "lock_with_pen", name: "Lock With Pen", icon: "🔏", packCode: "object"},
	{code: "shopping_bags", name: "Shopping Bags", icon: "🛍️", packCode: "object"},
	{code: "gift", name: "Wrapped Gift", icon: "🎁", packCode: "object"},
	{code: "balloon", name: "Balloon", icon: "🎈", packCode: "object"},
	{code: "party_popper", name: "Party Popper", icon: "🎉", packCode: "object"},
	{code: "confetti_ball", name: "Confetti Ball", icon: "🎊", packCode: "object"},
}

var symbolData = []emojiDef{
	{code: "red_heart", name: "Red Heart", icon: "❤️", packCode: "symbol"},
	{code: "orange_heart", name: "Orange Heart", icon: "🧡", packCode: "symbol"},
	{code: "yellow_heart", name: "Yellow Heart", icon: "💛", packCode: "symbol"},
	{code: "green_heart", name: "Green Heart", icon: "💚", packCode: "symbol"},
	{code: "blue_heart", name: "Blue Heart", icon: "💙", packCode: "symbol"},
	{code: "purple_heart", name: "Purple Heart", icon: "💜", packCode: "symbol"},
	{code: "brown_heart", name: "Brown Heart", icon: "🤎", packCode: "symbol"},
	{code: "black_heart", name: "Black Heart", icon: "🖤", packCode: "symbol"},
	{code: "white_heart", name: "White Heart", icon: "🤍", packCode: "symbol"},
	{code: "pink_heart", name: "Pink Heart", icon: "🩷", packCode: "symbol"},
	{code: "light_blue_heart", name: "Light Blue Heart", icon: "🩵", packCode: "symbol"},
	{code: "grey_heart", name: "Grey Heart", icon: "🩶", packCode: "symbol"},
	{code: "broken_heart", name: "Broken Heart", icon: "💔", packCode: "symbol"},
	{code: "heart_exclamation", name: "Heart Exclamation", icon: "❣️", packCode: "symbol"},
	{code: "two_hearts", name: "Two Hearts", icon: "💕", packCode: "symbol"},
	{code: "revolving_hearts", name: "Revolving Hearts", icon: "💞", packCode: "symbol"},
	{code: "sparkling_heart", name: "Sparkling Heart", icon: "💖", packCode: "symbol"},
	{code: "growing_heart", name: "Growing Heart", icon: "💗", packCode: "symbol"},
	{code: "beating_heart", name: "Beating Heart", icon: "💓", packCode: "symbol"},
	{code: "heart_with_arrow", name: "Heart With Arrow", icon: "💘", packCode: "symbol"},
	{code: "heart_with_ribbon", name: "Heart With Ribbon", icon: "💝", packCode: "symbol"},
	{code: "heart_decoration", name: "Heart Decoration", icon: "💟", packCode: "symbol"},
	{code: "hundred_points", name: "Hundred Points", icon: "💯", packCode: "symbol"},
	{code: "anger_symbol", name: "Anger Symbol", icon: "💢", packCode: "symbol"},
	{code: "collision", name: "Collision", icon: "💥", packCode: "symbol"},
	{code: "dizzy", name: "Dizzy", icon: "💫", packCode: "symbol"},
	{code: "sweat_droplets", name: "Sweat Droplets", icon: "💦", packCode: "symbol"},
	{code: "zzz", name: "Zzz", icon: "💤", packCode: "symbol"},
	{code: "check_mark", name: "Check Mark", icon: "✔️", packCode: "symbol"},
	{code: "check_box", name: "Check Box", icon: "☑️", packCode: "symbol"},
	{code: "cross_mark", name: "Cross Mark", icon: "❌", packCode: "symbol"},
	{code: "cross_mark_button", name: "Cross Mark Button", icon: "❎", packCode: "symbol"},
	{code: "heavy_plus", name: "Heavy Plus", icon: "➕", packCode: "symbol"},
	{code: "heavy_minus", name: "Heavy Minus", icon: "➖", packCode: "symbol"},
	{code: "heavy_division", name: "Heavy Division", icon: "➗", packCode: "symbol"},
	{code: "heavy_multiplication", name: "Heavy Multiplication", icon: "✖️", packCode: "symbol"},
	{code: "question_mark", name: "Question Mark", icon: "❓", packCode: "symbol"},
	{code: "grey_question", name: "Grey Question", icon: "❔", packCode: "symbol"},
	{code: "exclamation_mark", name: "Exclamation Mark", icon: "❗", packCode: "symbol"},
	{code: "grey_exclamation", name: "Grey Exclamation", icon: "❕", packCode: "symbol"},
	{code: "warning", name: "Warning", icon: "⚠️", packCode: "symbol"},
	{code: "prohibited", name: "Prohibited", icon: "🚫", packCode: "symbol"},
	{code: "no_entry", name: "No Entry", icon: "⛔", packCode: "symbol"},
	{code: "underage", name: "No One Under Eighteen", icon: "🔞", packCode: "symbol"},
	{code: "recycle", name: "Recycle", icon: "♻️", packCode: "symbol"},
	{code: "radioactive", name: "Radioactive", icon: "☢️", packCode: "symbol"},
	{code: "biohazard", name: "Biohazard", icon: "☣️", packCode: "symbol"},
	{code: "up_arrow", name: "Up Arrow", icon: "⬆️", packCode: "symbol"},
	{code: "down_arrow", name: "Down Arrow", icon: "⬇️", packCode: "symbol"},
	{code: "left_arrow", name: "Left Arrow", icon: "⬅️", packCode: "symbol"},
	{code: "right_arrow", name: "Right Arrow", icon: "➡️", packCode: "symbol"},
	{code: "up_right_arrow", name: "Up Right Arrow", icon: "↗️", packCode: "symbol"},
	{code: "down_right_arrow", name: "Down Right Arrow", icon: "↘️", packCode: "symbol"},
	{code: "down_left_arrow", name: "Down Left Arrow", icon: "↙️", packCode: "symbol"},
	{code: "up_left_arrow", name: "Up Left Arrow", icon: "↖️", packCode: "symbol"},
	{code: "left_right_arrow", name: "Left Right Arrow", icon: "↔️", packCode: "symbol"},
	{code: "up_down_arrow", name: "Up Down Arrow", icon: "↕️", packCode: "symbol"},
	{code: "red_circle", name: "Red Circle", icon: "🔴", packCode: "symbol"},
	{code: "orange_circle", name: "Orange Circle", icon: "🟠", packCode: "symbol"},
	{code: "yellow_circle", name: "Yellow Circle", icon: "🟡", packCode: "symbol"},
	{code: "green_circle", name: "Green Circle", icon: "🟢", packCode: "symbol"},
	{code: "blue_circle", name: "Blue Circle", icon: "🔵", packCode: "symbol"},
	{code: "purple_circle", name: "Purple Circle", icon: "🟣", packCode: "symbol"},
	{code: "brown_circle", name: "Brown Circle", icon: "🟤", packCode: "symbol"},
	{code: "black_circle", name: "Black Circle", icon: "⚫", packCode: "symbol"},
	{code: "white_circle", name: "White Circle", icon: "⚪", packCode: "symbol"},
	{code: "red_square", name: "Red Square", icon: "🟥", packCode: "symbol"},
	{code: "orange_square", name: "Orange Square", icon: "🟧", packCode: "symbol"},
	{code: "yellow_square", name: "Yellow Square", icon: "🟨", packCode: "symbol"},
	{code: "green_square", name: "Green Square", icon: "🟩", packCode: "symbol"},
	{code: "blue_square", name: "Blue Square", icon: "🟦", packCode: "symbol"},
	{code: "purple_square", name: "Purple Square", icon: "🟪", packCode: "symbol"},
	{code: "brown_square", name: "Brown Square", icon: "🟫", packCode: "symbol"},
	{code: "black_square", name: "Black Square", icon: "⬛", packCode: "symbol"},
	{code: "white_square", name: "White Square", icon: "⬜", packCode: "symbol"},
	{code: "tm", name: "Trademark", icon: "™️", packCode: "symbol"},
	{code: "copyright", name: "Copyright", icon: "©️", packCode: "symbol"},
	{code: "registered", name: "Registered", icon: "®️", packCode: "symbol"},
	{code: "currency_exchange", name: "Currency Exchange", icon: "💱", packCode: "symbol"},
	{code: "chart_up", name: "Chart Increasing", icon: "📈", packCode: "symbol"},
	{code: "chart_down", name: "Chart Decreasing", icon: "📉", packCode: "symbol"},
}

var flagData = []emojiDef{
	{code: "flag_vietnam", name: "Vietnam", icon: "VN", packCode: "flag"},
	{code: "flag_united_states", name: "United States", icon: "US", packCode: "flag"},
	{code: "flag_united_kingdom", name: "United Kingdom", icon: "GB", packCode: "flag"},
	{code: "flag_france", name: "France", icon: "FR", packCode: "flag"},
	{code: "flag_germany", name: "Germany", icon: "DE", packCode: "flag"},
	{code: "flag_italy", name: "Italy", icon: "IT", packCode: "flag"},
	{code: "flag_spain", name: "Spain", icon: "ES", packCode: "flag"},
	{code: "flag_portugal", name: "Portugal", icon: "PT", packCode: "flag"},
	{code: "flag_netherlands", name: "Netherlands", icon: "NL", packCode: "flag"},
	{code: "flag_belgium", name: "Belgium", icon: "BE", packCode: "flag"},
	{code: "flag_switzerland", name: "Switzerland", icon: "CH", packCode: "flag"},
	{code: "flag_austria", name: "Austria", icon: "AT", packCode: "flag"},
	{code: "flag_sweden", name: "Sweden", icon: "SE", packCode: "flag"},
	{code: "flag_norway", name: "Norway", icon: "NO", packCode: "flag"},
	{code: "flag_denmark", name: "Denmark", icon: "DK", packCode: "flag"},
	{code: "flag_finland", name: "Finland", icon: "FI", packCode: "flag"},
	{code: "flag_ireland", name: "Ireland", icon: "IE", packCode: "flag"},
	{code: "flag_poland", name: "Poland", icon: "PL", packCode: "flag"},
	{code: "flag_czechia", name: "Czechia", icon: "CZ", packCode: "flag"},
	{code: "flag_hungary", name: "Hungary", icon: "HU", packCode: "flag"},
	{code: "flag_russia", name: "Russia", icon: "RU", packCode: "flag"},
	{code: "flag_ukraine", name: "Ukraine", icon: "UA", packCode: "flag"},
	{code: "flag_turkey", name: "Turkey", icon: "TR", packCode: "flag"},
	{code: "flag_japan", name: "Japan", icon: "JP", packCode: "flag"},
	{code: "flag_south_korea", name: "South Korea", icon: "KR", packCode: "flag"},
	{code: "flag_north_korea", name: "North Korea", icon: "KP", packCode: "flag"},
	{code: "flag_china", name: "China", icon: "CN", packCode: "flag"},
	{code: "flag_taiwan", name: "Taiwan", icon: "TW", packCode: "flag"},
	{code: "flag_hong_kong", name: "Hong Kong", icon: "HK", packCode: "flag"},
	{code: "flag_macao", name: "Macao", icon: "MO", packCode: "flag"},
	{code: "flag_singapore", name: "Singapore", icon: "SG", packCode: "flag"},
	{code: "flag_thailand", name: "Thailand", icon: "TH", packCode: "flag"},
	{code: "flag_malaysia", name: "Malaysia", icon: "MY", packCode: "flag"},
	{code: "flag_indonesia", name: "Indonesia", icon: "ID", packCode: "flag"},
	{code: "flag_philippines", name: "Philippines", icon: "PH", packCode: "flag"},
	{code: "flag_myanmar", name: "Myanmar", icon: "MM", packCode: "flag"},
	{code: "flag_cambodia", name: "Cambodia", icon: "KH", packCode: "flag"},
	{code: "flag_laos", name: "Laos", icon: "LA", packCode: "flag"},
	{code: "flag_brunei", name: "Brunei", icon: "BN", packCode: "flag"},
	{code: "flag_india", name: "India", icon: "IN", packCode: "flag"},
	{code: "flag_pakistan", name: "Pakistan", icon: "PK", packCode: "flag"},
	{code: "flag_bangladesh", name: "Bangladesh", icon: "BD", packCode: "flag"},
	{code: "flag_sri_lanka", name: "Sri Lanka", icon: "LK", packCode: "flag"},
	{code: "flag_nepal", name: "Nepal", icon: "NP", packCode: "flag"},
	{code: "flag_australia", name: "Australia", icon: "AU", packCode: "flag"},
	{code: "flag_new_zealand", name: "New Zealand", icon: "NZ", packCode: "flag"},
	{code: "flag_canada", name: "Canada", icon: "CA", packCode: "flag"},
	{code: "flag_mexico", name: "Mexico", icon: "MX", packCode: "flag"},
	{code: "flag_brazil", name: "Brazil", icon: "BR", packCode: "flag"},
	{code: "flag_argentina", name: "Argentina", icon: "AR", packCode: "flag"},
	{code: "flag_chile", name: "Chile", icon: "CL", packCode: "flag"},
}

var numberData = []emojiDef{
	{code: "keycap_0", name: "Keycap 0", icon: "0️⃣", packCode: "number"},
	{code: "keycap_1", name: "Keycap 1", icon: "1️⃣", packCode: "number"},
	{code: "keycap_2", name: "Keycap 2", icon: "2️⃣", packCode: "number"},
	{code: "keycap_3", name: "Keycap 3", icon: "3️⃣", packCode: "number"},
	{code: "keycap_4", name: "Keycap 4", icon: "4️⃣", packCode: "number"},
	{code: "keycap_5", name: "Keycap 5", icon: "5️⃣", packCode: "number"},
	{code: "keycap_6", name: "Keycap 6", icon: "6️⃣", packCode: "number"},
	{code: "keycap_7", name: "Keycap 7", icon: "7️⃣", packCode: "number"},
	{code: "keycap_8", name: "Keycap 8", icon: "8️⃣", packCode: "number"},
	{code: "keycap_9", name: "Keycap 9", icon: "9️⃣", packCode: "number"},
	{code: "keycap_10", name: "Keycap 10", icon: "🔟", packCode: "number"},
	{code: "keycap_hash", name: "Keycap Hash", icon: "#️⃣", packCode: "number"},
	{code: "keycap_star", name: "Keycap Star", icon: "*️⃣", packCode: "number"},
}

func (s *EmojiSeeder) Run(db *gorm.DB) error {
	now := time.Now()

	packs := []model.EmojiPack{
		{Code: "face", Name: "Khuôn mặt", IsActive: true, CreatedAt: now, UpdatedAt: now},
		{Code: "animal", Name: "Động vật", IsActive: true, CreatedAt: now, UpdatedAt: now},
		{Code: "people", Name: "Con người", IsActive: true, CreatedAt: now, UpdatedAt: now},
		{Code: "food", Name: "Đồ ăn", IsActive: true, CreatedAt: now, UpdatedAt: now},
		{Code: "nature", Name: "Thiên nhiên", IsActive: true, CreatedAt: now, UpdatedAt: now},
		{Code: "travel", Name: "Du lịch", IsActive: true, CreatedAt: now, UpdatedAt: now},
		{Code: "activity", Name: "Hoạt động", IsActive: true, CreatedAt: now, UpdatedAt: now},
		{Code: "object", Name: "Đồ vật", IsActive: true, CreatedAt: now, UpdatedAt: now},
		{Code: "symbol", Name: "Ký hiệu", IsActive: true, CreatedAt: now, UpdatedAt: now},
		{Code: "flag", Name: "Quốc gia", IsActive: true, CreatedAt: now, UpdatedAt: now},
		{Code: "number", Name: "Số", IsActive: true, CreatedAt: now, UpdatedAt: now},
	}

	for i := range packs {
		if err := db.Clauses(clause.OnConflict{
			Columns:   []clause.Column{{Name: "code"}},
			DoUpdates: clause.AssignmentColumns([]string{"name", "is_active", "updated_at"}),
		}).Create(&packs[i]).Error; err != nil {
			return fmt.Errorf("emoji pack %q: %w", packs[i].Code, err)
		}
	}

	// Build pack code→id map
	var allPacks []model.EmojiPack
	if err := db.Find(&allPacks).Error; err != nil {
		return fmt.Errorf("fetch emoji packs: %w", err)
	}
	packIDByCode := make(map[string]uint, len(allPacks))
	for _, p := range allPacks {
		packIDByCode[p.Code] = p.ID
	}

	allDefs := make([]emojiDef, 0)
	allDefs = append(allDefs, faceData...)
	allDefs = append(allDefs, animalData...)
	allDefs = append(allDefs, peopleData...)
	allDefs = append(allDefs, foodData...)
	allDefs = append(allDefs, natureData...)
	allDefs = append(allDefs, travelData...)
	allDefs = append(allDefs, activityData...)
	allDefs = append(allDefs, objectData...)
	allDefs = append(allDefs, symbolData...)
	allDefs = append(allDefs, flagData...)
	allDefs = append(allDefs, numberData...)

	for _, d := range allDefs {
		pid := packIDByCode[d.packCode]

		sourceType := "unicode_icon"
		sourceValue := d.icon
		if d.packCode == "flag" {
			sourceType = "flag"
			sourceValue = d.code
		}

		iconText := d.icon
		e := model.Emoji{
			Code:        d.code,
			Name:        d.name,
			PackID:      &pid,
			AssetURL:    "",
			SourceType:  sourceType,
			SourceValue: sourceValue,
			IconText:    &iconText,
			Status:      1,
			CreatedAt:   now,
			UpdatedAt:   now,
		}
		if err := db.Clauses(clause.OnConflict{
			Columns:   []clause.Column{{Name: "code"}},
			DoUpdates: clause.AssignmentColumns([]string{"name", "pack_id", "source_type", "source_value", "icon_text", "updated_at"}),
		}).Create(&e).Error; err != nil {
			return fmt.Errorf("emoji %q: %w", d.code, err)
		}
	}

	fmt.Printf("[EmojiSeeder] seeded %d emoji packs and %d emojis\n", len(packs), len(allDefs))
	return nil
}
