# rabbitmq/rabbitmq.conf

listeners.tcp.default = 5672

management.tcp.port = 15672

default_user = admin
default_pass = admin

log.console = true
log.console.level = info

vm_memory_high_watermark.relative = 0.6

disk_free_limit.absolute = 1GB